/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dilemazatvorenikanew;


import java.awt.Color;
import java.util.Random;
import javax.swing.*;
/**
 *
 * @author Cheda
 */
public class IgracRacunar extends javax.swing.JFrame {

    /**
     * Creates new form IgracRacunar
     */
    public int S;
    public int R;
    public int T;
    public int P;
    public int s;
    public int r;
    public int t;
    public int p;
    public int k = 0;
    public int i = 0;
    public int j = 0;
    public int[] a;
    public int[] b;
    public double suma1 = 0;
    public double suma2 = 0;
    public double[] rezultat1;
    public double[] rezultat2;
    public int strategija;
    public boolean provera1=false;
    public boolean provera2=false;
    public boolean rend = false;
    Strategije st = new Strategije();
    public IgracRacunar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Igrač vs Računar");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Igrač 1")));
        jPanel1.setPreferredSize(new java.awt.Dimension(239, 118));

        jButton1.setText("Ne priznaj - C");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Priznaj - D");
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Rezultat:");

        jTextField1.setEditable(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Računar"));
        jPanel2.setPreferredSize(new java.awt.Dimension(239, 118));

        jLabel6.setText("Rezultat:");

        jTextField2.setEditable(false);

        jLabel7.setText("Strategija:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TitForTat", "TitFor2Tat", "Pavlov", "Spite", "Rendom m", "SoftMajo", "Random" }));
        jComboBox1.setSelectedItem(null);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(10, 10, 10)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Matrica Plaćanja"));
        jPanel3.setPreferredSize(new java.awt.Dimension(239, 197));

        jLabel2.setText("R- nagrada za nepriznavanje:");

        jLabel3.setText("T- iskušenje za priznanje:");

        jLabel4.setText("S- isplata za naivnost:");

        jLabel5.setText("P- kazna za priznavanje :");

        jTextField10.setBackground(new java.awt.Color(204, 204, 204));
        jTextField10.setEditable(false);
        jTextField10.setText("30");

        jTextField11.setBackground(new java.awt.Color(204, 204, 204));
        jTextField11.setEditable(false);
        jTextField11.setText("50");

        jTextField12.setBackground(new java.awt.Color(204, 204, 204));
        jTextField12.setEditable(false);
        jTextField12.setText("0");

        jTextField13.setBackground(new java.awt.Color(204, 204, 204));
        jTextField13.setEditable(false);
        jTextField13.setText("10");

        jButton7.setText("Promeni");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Sačuvaj");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jTextField3.setText("30");

        jTextField4.setBackground(new java.awt.Color(204, 204, 204));
        jTextField4.setText("50");

        jTextField5.setBackground(new java.awt.Color(204, 204, 204));
        jTextField5.setText("0");

        jTextField6.setBackground(new java.awt.Color(204, 204, 204));
        jTextField6.setText("10");

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Igrač");

        jLabel13.setText("Računar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jTextField12, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                                        .addComponent(jTextField13))
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                                .addComponent(jTextField5)
                                .addComponent(jTextField6)
                                .addComponent(jTextField3))
                            .addComponent(jLabel13))))
                .addGap(15, 15, 15))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton7, jButton8});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton7))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Rezultati"));
        jPanel5.setPreferredSize(new java.awt.Dimension(196, 213));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jButton5.setText("Grafik");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 146, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap())
        );

        jButton3.setText("Start");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Nova Igra");
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setText("Broj iteracija");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Random", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25" }));
        jComboBox2.setSelectedItem(null);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dilemazatvorenikanew/mat2.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton3, jButton4});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-538)/2, (screenSize.height-540)/2, 538, 540);
    }// </editor-fold>//GEN-END:initComponents
     public void ukljuciDugme (JButton dugme1, JButton dugme2)
    {
        dugme1.setEnabled(true);
        dugme2.setEnabled(true);
    }
    public void iskljuciDugme (JButton dugme1, JButton dugme2)
    {
        dugme1.setEnabled(false);
        dugme2.setEnabled(false);
    }
    public void proveriParm(int r, int t, int s, int p)
    {
        if (r>t)
          throw new IllegalArgumentException();
        if (p>r)
          throw new IllegalArgumentException();
        if (s>p)
          throw new IllegalArgumentException();
    }
    public String vratiImeStrategije(int s)
    {
        switch (s)
        {
            case 1: return "TitForTat";
            case 2: return "TitFor2Tat";
            case 3: return "Pavlov";
            case 4: return "Spite";
            case 5: return "RendomMoves";
            case 6: return "SoftMajo";
        }
        return "";
    }
    public void napuniMatricu ()
    {
        R = Integer.parseInt(jTextField10.getText());
        T = Integer.parseInt(jTextField11.getText());
        S = Integer.parseInt(jTextField12.getText());
        P = Integer.parseInt(jTextField13.getText());
        r = Integer.parseInt(jTextField3.getText());
        t = Integer.parseInt(jTextField4.getText());
        s = Integer.parseInt(jTextField5.getText());
        p = Integer.parseInt(jTextField6.getText());
        proveriParm(r, t, s, p);
        proveriParm(R, T, S, P);
    }
    public String vratiZnak(int b)
    {
        if (b==0)
           return "D";
        else
           return "C";
    }
    public void funkcijaPlacanjaC(int b)
    {
       if (b==1)
               {
                   suma1=(suma1+R);
                   suma2=(suma2+r);
                   rezultat1[i] = suma1/(i+1);
                   rezultat2[i] = suma2/(i+1);
               }
               else 
               {
                   suma1=(suma1+S);
                   suma2=(suma2+t);
                   rezultat1[i] = suma1/(i+1);
                   rezultat2[i] = suma2/(i+1);
               } 
    }
    public void funkcijaPlacanjaD(int b)
    {
         if (b==1)
               {
                   suma1=(suma1+T);
                   suma2=(suma2+s);
                   rezultat1[i] = suma1/(i+1);
                   rezultat2[i] = suma2/(i+1);
               }
               else 
               {
                   suma1=(suma1+P);
                   suma2=(suma2+p);
                   rezultat1[i] = suma1/(i+1);
                   rezultat2[i] = suma2/(i+1);
               }
    }
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jTextField10.setBackground(Color.WHITE);
        jTextField11.setBackground(Color.WHITE);
        jTextField12.setBackground(Color.WHITE);
        jTextField13.setBackground(Color.WHITE);
        jTextField3.setBackground(Color.WHITE);
        jTextField4.setBackground(Color.WHITE);
        jTextField5.setBackground(Color.WHITE);
        jTextField6.setBackground(Color.WHITE);
        jTextField10.setEditable(true);
        jTextField11.setEditable(true);
        jTextField12.setEditable(true);
        jTextField13.setEditable(true);
        jTextField3.setEditable(true);
        jTextField4.setEditable(true);
        jTextField5.setEditable(true);
        jTextField6.setEditable(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
        napuniMatricu();
        jTextField10.setEditable(false);
        jTextField11.setEditable(false);
        jTextField12.setEditable(false);
        jTextField13.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField5.setEditable(false);
        jTextField6.setEditable(false);
        jTextField10.setBackground(Color.LIGHT_GRAY);
        jTextField11.setBackground(Color.LIGHT_GRAY);
        jTextField12.setBackground(Color.LIGHT_GRAY);
        jTextField13.setBackground(Color.LIGHT_GRAY);
        jTextField3.setBackground(Color.LIGHT_GRAY);
        jTextField4.setBackground(Color.LIGHT_GRAY);
        jTextField5.setBackground(Color.LIGHT_GRAY);
        jTextField6.setBackground(Color.LIGHT_GRAY);
        }
        catch (IllegalArgumentException e)
        {
             JOptionPane.showMessageDialog(null, "Parametri su pogrešno uneti!!!", "InfoBox: ", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        provera1 = true;
        JComboBox cb = (JComboBox)evt.getSource();
        String broj = (String)cb.getSelectedItem();
        if (broj == "Random")
           {
               Random rg = new Random();
               k = rg.nextInt(25)+1;
               
           }
        else
        {
            k = Integer.parseInt(broj);
        }
        a = new int[k];
        b = new int[k];
        rezultat1 = new double[k];
        rezultat2 = new double[k];
        if(provera1&&provera2)
            jButton3.setEnabled(true);
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ukljuciDugme(jButton1, jButton2);
        napuniMatricu();
        jTextField1.setText("0");
        jTextField2.setText("0");
        iskljuciDugme(jButton7, jButton8);
        iskljuciDugme(jButton3, jButton5);
        jComboBox1.setEnabled(false);
        jComboBox2.setEnabled(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        provera2 = true;
        JComboBox cb1 = (JComboBox)evt.getSource();
        String str = (String)cb1.getSelectedItem();
        if (str == "Random")
           {
               Random rg = new Random();
               strategija = rg.nextInt(6)+1;
               rend = true;
           }
        else
        {
            switch (str)
            {
             case "TitForTat":
                   strategija = 1;
                   break;
             case "TitFor2Tat":
                   strategija = 2;
                   break;
             case "Pavlov":
                   strategija = 3;
                   break;
             case "Spite":
                   strategija = 4;
                   break;
             case "Rendom m":
                   strategija = 5;
                   break;
             case "SoftMajo":
                   strategija = 6;
                   break;
            }
            rend = false;
        }
        if(provera1&&provera2)
            jButton3.setEnabled(true);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        a[i] = 1; // odigrao je cooperate

        switch (strategija)
        {
            case 1:
               b[i] = st.tft(a, i);
               funkcijaPlacanjaC(b[i]);
               jTextField1.setText(String.format( "%.2f", rezultat1[i] ));
               jTextField2.setText(String.format( "%.2f", rezultat2[i] ));
               jTextArea2.append(i+1+": Igrac-"+"C "+"vs Racunar-"+vratiZnak(b[i]) +"\n");
               break;
            case 2:
               b[i] = st.tf2t(a, i);
               funkcijaPlacanjaC(b[i]);
               jTextField1.setText(String.format( "%.2f", rezultat1[i] ));
               jTextField2.setText(String.format( "%.2f", rezultat2[i] ));
               jTextArea2.append(i+1+": Igrac-"+"C "+"vs Racunar-"+vratiZnak(b[i])+"\n");
               break;
            case 3:
               b[i] = st.Pavlov(a, b, i);
               funkcijaPlacanjaC(b[i]);
               jTextField1.setText(String.format( "%.2f", rezultat1[i] ));
               jTextField2.setText(String.format( "%.2f", rezultat2[i] ));
               jTextArea2.append(i+1+": Igrac-"+"C "+"vs Racunar-"+vratiZnak(b[i])+"\n");
               break;
            case 4:
               b[i] = st.spite(a, i);
               funkcijaPlacanjaC(b[i]);
               jTextField1.setText(String.format( "%.2f", rezultat1[i] ));
               jTextField2.setText(String.format( "%.2f", rezultat2[i] ));
               jTextArea2.append(i+1+": Igrac-"+"C "+"vs Racunar-"+vratiZnak(b[i])+"\n");
               break;
            case 5:
               b[i] = st.random_m();
               funkcijaPlacanjaC(b[i]);
               jTextField1.setText(String.format( "%.2f", rezultat1[i] ));
               jTextField2.setText(String.format( "%.2f", rezultat2[i] ));
               jTextArea2.append(i+1+": Igrac-"+"C "+"vs Racunar-"+vratiZnak(b[i])+"\n");
               break;
            case 6:
               b[i] = st.softMajo(a, i);
               funkcijaPlacanjaC(b[i]);
               jTextField1.setText(String.format( "%.2f", rezultat1[i] ));
               jTextField2.setText(String.format( "%.2f", rezultat2[i] ));
               jTextArea2.append(i+1+": Igrac-"+"C "+"vs Racunar-"+vratiZnak(b[i])+"\n");
               break;
            
        }
        i++;
        if (i==k)
        {
            iskljuciDugme(jButton1, jButton2);
            jButton4.setEnabled(true);
            jButton5.setEnabled(true);
            if (rend == true)
            jTextArea2.append("\n"+"Strategija koju je računar koristio:"+ "\n" +vratiImeStrategije(strategija));
             if (rezultat1[i-1]==rezultat2[i-1])
            {
                  jLabel9.setText("Nerešeno!");
                  jLabel10.setText("Nerešeno!");
            }
            else
                if (rezultat1[i-1]>rezultat2[i-1])
                  jLabel9.setText("Pobednik!");
                else
                  jLabel10.setText("Pobednik!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        a[i]= 0; // odigrao je deflect
        switch (strategija)
        {
            case 1:
               b[i] = st.tft(a, i);
               funkcijaPlacanjaD(b[i]);
               jTextField1.setText(String.format( "%.2f", rezultat1[i] ));
               jTextField2.setText(String.format( "%.2f", rezultat2[i] ));
               jTextArea2.append(i+1+": Igrac-"+"D "+"vs Racunar-"+vratiZnak(b[i])+"\n");
               break;
            case 2:
               b[i] = st.tf2t(a, i);
               funkcijaPlacanjaD(b[i]);
               jTextField1.setText(String.format( "%.2f", rezultat1[i] ));
               jTextField2.setText(String.format( "%.2f", rezultat2[i] ));
               jTextArea2.append(i+1+": Igrac-"+"D "+"vs Racunar-"+vratiZnak(b[i])+"\n");
               break;
            case 3:
               b[i] = st.Pavlov(a, b, i);
               funkcijaPlacanjaD(b[i]);
               jTextField1.setText(String.format( "%.2f", rezultat1[i] ));
               jTextField2.setText(String.format( "%.2f", rezultat2[i] ));
               jTextArea2.append(i+1+": Igrac-"+"D "+"vs Racunar-"+vratiZnak(b[i])+"\n"); 
               break;
            case 4:
               b[i] = st.spite(a, i);
               funkcijaPlacanjaD(b[i]);
               jTextField1.setText(String.format( "%.2f", rezultat1[i] ));
               jTextField2.setText(String.format( "%.2f", rezultat2[i] ));
               jTextArea2.append(i+1+": Igrac-"+"D "+"vs Racunar-"+vratiZnak(b[i])+"\n");
               break;
            case 5:
               b[i] = st.random_m();
               funkcijaPlacanjaD(b[i]);
               jTextField1.setText(String.format( "%.2f", rezultat1[i] ));
               jTextField2.setText(String.format( "%.2f", rezultat2[i] ));
               jTextArea2.append(i+1+": Igrac-"+"D "+"vs Racunar-"+vratiZnak(b[i])+"\n");
               break;
            case 6:
               b[i] = st.softMajo(a, i);
               funkcijaPlacanjaD(b[i]);
               jTextField1.setText(String.format( "%.2f", rezultat1[i] ));
               jTextField2.setText(String.format( "%.2f", rezultat2[i] ));
               jTextArea2.append(i+1+": Igrac-"+"D "+"vs Racunar-"+vratiZnak(b[i])+"\n");
               break;
        }
        i++;
        if (i==k)
        {
            jButton4.setEnabled(true);
            jButton5.setEnabled(true);
            iskljuciDugme(jButton1, jButton2);
            if (rend == true)
            jTextArea2.append("\n"+"Strategija koju je računar koristio:"+ "\n" +vratiImeStrategije(strategija));
            if (rezultat1[i-1]==rezultat2[i-1])
            {
                  jLabel9.setText("Nerešeno!");
                  jLabel10.setText("Nerešeno!");
            }
            else
                if (rezultat1[i-1]>rezultat2[i-1])
                  jLabel9.setText("Pobednik!");
                else
                  jLabel10.setText("Pobednik!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
           i= 0;
           j= 0;
           suma1 = 0;
           suma2 = 0;
           jTextField1.setText("0");
           jTextField2.setText("0");
           jLabel9.setText(null);
           jLabel10.setText(null);
           jTextArea2.setText(null);
           jButton3.setEnabled(true);
           ukljuciDugme(jButton7, jButton8);
           jButton5.setEnabled(false);
           jComboBox1.setEnabled(true);
           jComboBox2.setEnabled(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      Grafik gr1 = new Grafik();
      gr1.napraviGrafik(rezultat1, rezultat2, i,"Igrač 1","Računar");
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IgracRacunar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IgracRacunar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IgracRacunar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IgracRacunar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new IgracRacunar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
